### ISSUE TITLE
Second part of the skating loss

### ISSUE THREAD

**Issue by JiahaoPlus** [jiashunwang/Long-term-Motion-in-3D-Scenes#1]
Hi Jiashun, thanks for your nice work! Could you please illustrate more about the intuition behind this for loop? 
https://github.com/jiashunwang/Long-term-Motion-in-3D-Scenes/blob/5673d342093ff92e677da2d90e0dd8b7dd766c5b/utils_optimize.py#L312

**Comment by jiashunwang** [comment]
Hi, Jiahao
So let's say in the first period, the left foot is the stable foot and in the second period, the right foot is the stable foot. We want the right foot in the last frame of the first period to be close to the stable foot location in the next peirod, since it is  going to be the stable foot in the next frame. We want this to be smooth.

Sorry for the messy code here. I will rewrite the optimization part in the summer.

**Comment by JiahaoPlus** [comment]
Thanks for your illustration. That's helpful.
